[package]
name = "aoc"
version = "0.1.0"
edition = "2024"
authors = ["Harsh V Srivastava <harshvsri@gamil.com>"]
description = "Advent of Code solutions"
keywords = ["aoc", "puzzles", "algorithms", "mathematics"]

[profile.release]
debug = true
panic = "abort"
# lto = "fat"
# strip = true
# overflow-checks = true

[dependencies]
nalgebra = "0.34.1"
once_cell = "1.21.3"
regex = "1.11.1"
